global:
  iotFlow:
    maxConnections: 5

kafka-cluster:
  priorityClassName: thingpark-data
  kafka:
    resources:
      limits:
        memory: 700Mi
  zookeeper:
    resources:
      limits:
        memory: 200Mi
      requests:
        memory: 200Mi

mongo-replicaset:
  replicaSet:
    resources:
      limits:
        memory: 850Mi
    priorityClassName: thingpark-data

  arbiter:
    resources:
      limits:
        memory: 200Mi
    priorityClassName: thingpark-data

zookeeper:
  priorityClassName: thingpark-data
  resources:
    limits:
      memory: 150Mi
    requests:
      memory: 150Mi

mariadb-galera:
  priorityClassName: thingpark-data
  resources:
    limits:
      memory: 800Mi
    requests:
      memory: 400Mi
  mariadbConfiguration: |-
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    plugin_dir=/opt/bitnami/mariadb/plugin

    [mysqld]
    explicit_defaults_for_timestamp=1
    ###explicit_defaults_for_timestamp
    default_storage_engine=InnoDB
    basedir=/opt/bitnami/mariadb
    datadir=/bitnami/mariadb/data
    plugin_dir=/opt/bitnami/mariadb/plugin
    tmpdir=/opt/bitnami/mariadb/tmp
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid
    bind_address=0.0.0.0

    ## Character set
    ###collation_server=utf8_unicode_ci
    collation_server=utf8_general_ci
    ###init_connect='SET NAMES utf8'
    character_set_server=utf8

    ## MyISAM
    key_buffer_size=1M
    myisam_recover_options=FORCE,BACKUP

    ## Safety
    skip_host_cache
    skip_name_resolve
    ### max_allowed_packet=16M
    max_allowed_packet=64M
    max_connect_errors=1000000
    sql_mode=STRICT_TRANS_TABLES
    ### sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
    sysdate_is_now=1

    ## Binary Logging
    log_bin=mysql-bin
    expire_logs_days=14
    # Disabling for performance per http://severalnines.com/blog/9-tips-going-production-galera-cluster-mysql
    sync_binlog=0
    # Required for Galera
    binlog_format=row

    ## Caches and Limits
    tmp_table_size=32M
    max_heap_table_size=32M
    query_cache_type=0
    query_cache_size=0
    ### max_connections=500
    max_connections=120
    ### thread_cache_size=50
    thread_cache_size=200
    ### Added
    back-log=128
    open_files_limit=65535
    table_definition_cache=4096
    table_open_cache=4096

    ## InnoDB
    innodb=FORCE
    innodb_strict_mode=OFF
    # Mandatory per https://github.com/codership/documentation/issues/25
    innodb_autoinc_lock_mode=2
    # Per https://www.percona.com/blog/2006/08/04/innodb-double-write/
    innodb_doublewrite=1
    innodb_flush_method=O_DIRECT
    innodb_log_files_in_group=2
    innodb_log_file_size=128M
    innodb_file_per_table=1
    # 80% Memory is default reco.
    # Need to re-evaluate when DB size grows
    innodb_buffer_pool_instances=1
    innodb_buffer_pool_chunk_size=128M
    innodb_buffer_pool_size=128M
    innodb_log_buffer_size=64M
    innodb_file_format=Barracuda

    ## Logging
    log_error=/opt/bitnami/mariadb/logs/mysqld.log
    slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
    log_queries_not_using_indexes=1
    slow_query_log=1

    optimizer_search_depth                   = 0
    optimizer_switch                         = 'index_merge=on'
    optimizer_switch                         = 'index_merge_union=on'
    optimizer_switch                         = 'index_merge_sort_union=on'
    optimizer_switch                         = 'index_merge_intersection=on'
    optimizer_switch                         = 'index_merge_sort_intersection=off'
    optimizer_switch                         = 'index_condition_pushdown=on'
    optimizer_switch                         = 'derived_merge=on'
    optimizer_switch                         = 'derived_with_keys=on'
    optimizer_switch                         = 'firstmatch=on'
    optimizer_switch                         = 'loosescan=on'
    optimizer_switch                         = 'materialization=on'
    optimizer_switch                         = 'in_to_exists=on'
    optimizer_switch                         = 'semijoin=on'
    optimizer_switch                         = 'partial_match_rowid_merge=on'
    optimizer_switch                         = 'partial_match_table_scan=on'
    optimizer_switch                         = 'subquery_cache=on,mrr=on'
    optimizer_switch                         = 'mrr_cost_based=on'
    optimizer_switch                         = 'mrr_sort_keys=off'
    optimizer_switch                         = 'outer_join_with_cache=on'
    optimizer_switch                         = 'semijoin_with_cache=on'
    optimizer_switch                         = 'join_cache_incremental=on'
    optimizer_switch                         = 'join_cache_hashed=on'
    optimizer_switch                         = 'join_cache_bka=on'
    optimizer_switch                         = 'optimize_join_buffer_size=on'
    optimizer_switch                         = 'table_elimination=on'
    optimizer_switch                         = 'extended_keys=on'

    join-buffer-space-limit                  = 4M
    join-cache-level                         = 6
    join-buffer-size                         = 4M

    [galera]
    wsrep_on=ON
    wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
    wsrep_sst_method=mariabackup
    wsrep_slave_threads=4
    wsrep_cluster_address=gcomm://
    wsrep_cluster_name=galera
    wsrep_sst_auth="root:"
    wsrep_provider_options = "gcache.size=2G;gcs.fc_limit=60;gcs.fc_factor=0.8; gmcast.segment=0"
    innodb_flush_log_at_trx_commit=2
    # MYISAM REPLICATION SUPPORT #
    wsrep_replicate_myisam=ON

    ### Maximum number of rows in write set
    wsrep_max_ws_rows                        = 0
    ### Maximum size of write set
    wsrep_max_ws_size                        = 1073741824

    [mariadb]
    plugin_load_add=auth_pam

sql-proxy:
  priorityClassName: thingpark-data-path
  replicaCount: 2
  resources:
    limits:
      memory: 150Mi

lrc:
  priorityClassName: thingpark-data-path
  replicaCount: 2
  lrc:
    resources:
      limits:
        memory: 250Mi
    lrcIni:
      kafkalateul:
        enabled: 1
        limiter: 2
        minDelay: 1000
  lnsBridge:
    resources:
      limits:
        memory: 50Mi
  lrcSync:
    resources:
      limits:
        memory: 100Mi
  sftp:
    resources:
      limits:
        memory: 50Mi
  rfscanBatch:
    resources:
      limits:
        memory: 50Mi

lrc-proxy:
  priorityClassName: thingpark-data-path
  replicaCount: 2
  resources:
    limits:
      memory: 50Mi

support:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 100Mi

wireless-pki:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 880Mi

cups-server:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 50Mi

locsolver:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 50Mi

tp-gui:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 50Mi

smp-tpe:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 60Mi

twa:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 800Mi

twa-admin:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 100Mi

twa-dev:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 600Mi

twa-ran:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 600Mi

twa-task-res:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 300Mi

twa-alarm-notif:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 50Mi

task-notif-ws:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 300Mi

tpx-flow:
  priorityClassName: thingpark-data-path
  engine:
    replicaCount: 2
    resources:
      limits:
        memory: 250Mi
  supervisor:
    replicaCount: 1
    resources:
      limits:
        memory: 300Mi
  hub:
    replicaCount: 2
    resources:
      limits:
        memory: 300Mi
  bridge:
    replicaCount: 1
    resources:
      limits:
        memory: 300Mi
  api:
    replicaCount: 2
    resources:
      limits:
        memory: 300Mi

tp-dx:
  priorityClassName: thingpark-data-path
  replicaCount: 1
  resources:
    limits:
      memory: 300Mi

node-red:
  priorityClassName: thingpark-data-path
  replicaCount: 1
  resources:
    limits:
      memory: 100Mi

nssa:
  priorityClassName: thingpark-enterprise-services
  networkSurvey:
    replicaCount: 1
    resources:
      limits:
        memory: 50Mi
  spectrumAnalysis:
    replicaCount: 1
    resources:
      limits:
        memory: 50Mi

wlogger:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 150Mi

shellinabox:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 50Mi

# Configuration for controllers
ingress-nginx:
  controller:
    priorityClassName: thingpark-data-path
    resources:
      limits:
        memory: 384Mi
