# Mandatory & additional usual values to define for a Thingpark Data Stack.
# Advanced settings detailed in chart values file
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values allow Actility registry usage by authenticate using "thingpark-image-pull-secret" secret
global:
  imagePullSecrets: 
  - "thingpark-image-pull-secret"
  
psmdb-operator:
  imagePullSecrets:
    - name: "thingpark-image-pull-secret"
  image:
    # repository: "<private-registry>/percona-server-mongodb-operator"
strimzi-kafka-operator:
  image:
    imagePullSecrets: "thingpark-image-pull-secret"
    # registry: "<private-registry>"

mariadb-galera:
#  rootUser:
#    password: "<custom-password>"
  image:
    # registry: "<private-registry>"

zookeeper:
  image:
    # registry: "<private-registry>"

mongo-replicaset:
  imagePullSecrets: 
  - name: "thingpark-image-pull-secret"
  mongoDbInit:
    image:
      # repository: "<private-registry>"
  mongoDbServer:
    image:
      # repository: "<private-registry>"
  accounts:
    admin:
      password: "<custom-password>"
    userAdmin:
      password: "<custom-password>"
    userBackup:
      password: "<custom-password>"
    clusterMonitor:
      password: "<custom-password>"
    pmm:
      password: "<custom-password>"

kafka-cluster:
  imagePullSecrets: 
  - name: "thingpark-image-pull-secret"
  kafka:
    image:
      # repository: "<private-registry>"
  zookeeper:
    image:
      # repository: "<private-registry>"
  operator:
    image:
      # repository: "<private-registry>"
